name: interop

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      impls:
        description: "QUIC Implementations"
        required: true
        default: '["linuxquic", "msquic", "neqo", "ngtcp2", "picoquic", "quiche"]'

jobs:
  interop:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        impl: ${{ fromJSON(github.event.inputs.impls || '["linuxquic", "msquic", "neqo", "ngtcp2", "picoquic", "quiche"]') }}

    steps:
      - name: Install tshark
        run: |
          sudo add-apt-repository ppa:wireshark-dev/nightly
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends tshark

      - name: Setup docker
        uses: docker/setup-docker-action@v4
        with:
          version: version=v28.3.0

      - name: Checkout linuxquic
        uses: actions/checkout@v5

      - name: Install Linux QUIC module
        run: |
          sed -i '/LIBGNUTLS/d' configure.ac
          ./autogen.sh && ./configure --prefix=/usr
          sudo make -C modules install

      - name: Checkout quic-interop-runner
        uses: actions/checkout@v5
        with:
          repository: quic-interop/quic-interop-runner
          path: quic-interop-runner

      - name: Run interop tests
        run: |
          cd quic-interop-runner
          pip install -U pip
          pip install -r requirements.txt

          # Ensure linuxquic entry exists
          jq '.linuxquic //= {"image": "quay.io/lxin/linuxquic-interop:latest", "url": "https://github.com/lxin/quic", "role": "both"}' implementations_quic.json > temp.json
          mv -f temp.json implementations_quic.json

          python3 run.py -t onlyTests -c linuxquic -s ${{ matrix.impl }} | tee output.log # linuxquic -> impl
          awk -F',' '/✕\(/ { match($0, /✕\((.*)\)/, a); if(split(a[1],b,",")>3) exit 1 }' output.log || exit 1 # Fail if failures > 3

          [ "${{ matrix.impl }}" = "linuxquic" ] && exit 0 # Skip the reverse test if both server and client are linuxquic

          python3 run.py -t onlyTests -c ${{ matrix.impl }} -s linuxquic | tee output.log # impl -> linuxquic
          awk -F',' '/✕\(/ { match($0, /✕\((.*)\)/, a); if(split(a[1],b,",")>3) exit 1 }' output.log || exit 1
